# pylint: disable=E1101:no-member,C0103:invalid-name

"""add tenders table

Revision ID: 6c46d663f42d
Revises: 8d5819f222d9
Create Date: 2026-03-27 15:25:23.931479

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "6c46d663f42d"
down_revision: Union[str, Sequence[str], None] = "8d5819f222d9"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "tenders",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("tender_number", sa.Integer(), nullable=False),
        sa.Column("tender_year", sa.Integer(), nullable=False),
        sa.Column("object_description", sa.String(), nullable=False),
        sa.Column("public_body_name", sa.String(), nullable=False),
        sa.Column(
            "modality",
            sa.Enum(
                "PUBLIC_TENDER",
                "PRICE_QUOTATION",
                "INVITATION",
                "AUCTION",
                "CONTEST",
                "TRADING_SESSION",
                "DIRECT_CONTRACTING",
                name="tendermodality",
            ),
            nullable=False,
        ),
        sa.Column(
            "format",
            sa.Enum("ELECTRONIC", "IN_PERSON", name="tenderformat"),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum(
                "MONITORING",
                "ANALYSIS",
                "APPROVED",
                "REJECTED",
                "REGISTERED",
                "IN_PROGRESS",
                "APPEAL",
                "FINISHED",
                "SUSPENDED",
                "CANCELED",
                name="tenderstatus",
            ),
            nullable=False,
        ),
        sa.Column(
            "participation_result",
            sa.Enum("PENDING", "WON", "LOST", name="participationresult"),
            nullable=True,
        ),
        sa.Column("awarded_value", sa.Numeric(), nullable=True),
        sa.Column("session_date", sa.DateTime(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column("company_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["company_id"],
            ["companies.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("tenders")
    # ### end Alembic commands ###
